#!/usr/bin/env python3
"""The AI exposure module stays display-only, and stays qualified.

WHY THIS EXISTS. AI_EXPOSURE_BY_SOC_GROUP appeared in no check_*.py at all,
which made it the one module in this app with nothing underneath it, and it
is the module most likely to be edited on a headline. Its safety property is
a single sentence -- it moves no salary, no loan and no premium -- and that
property was enforced by nobody having broken it yet.

The second half is newer. Until 2026-09-09 the module ended every Medium and
High band with a "lower-exposure alternative", the one thing in it that
behaved like advice. Manning and Aguirre (NBER w34705, 2026) pair the SAME
Eloundou measure this module bands with an index of how well workers could
absorb a job loss, and find the two POSITIVELY correlated: the most exposed
occupations are on average held by the people best placed to move. So the
steering pointed at the group least likely to need it. Worse, the
concentrated vulnerability they find is ten occupations of which eight are
entered with a high school diploma or less, which puts it on the
COUNTERFACTUAL side of every comparison this app makes rather than on the
degree side it scores.

The steering was deleted and AI_EXPOSURE_CAPACITY_NOTE replaces it. A note
like that decays in one direction: someone trims it to the reassuring half
and it becomes a reason to stop worrying, or to the alarming half and it
becomes a reason to avoid a field. So this asserts BOTH HALVES ARE PRESENT,
the same rule check_chart_basis holds for the refinance and restructure
disclosures.

WHAT IT ASSERTS:

  1. The bands are well formed and monotone in score. A typo that puts a Low
     score above a Medium one silently reorders the whole scale.
  2. Every SOC major group in MAJOR_DATA has an entry, so no occupation
     falls to the "Unclassified" placeholder by accident.
  3. THE MODULE MOVES NO MONEY. No function outside a small allowlist may
     read the exposure names, checked by AST. This is the property the
     module's whole design rests on and the one nothing else checks.
  4. The steering function is GONE. An API that is absent cannot be
     misused, the check_pdf_concurrency argument.
  5. The note carries both halves, anchored on figures TRANSCRIBED FROM THE
     PAPER rather than read back off the constant under test.
  6. The note reaches the screen AND the PDF. The report printed the band
     alone, which is exactly the half that reads as a warning: the chart
     twin rule arriving in prose.
  7. The paper's ten high-vulnerability occupations resolve in MAJOR_DATA,
     and the education split is what the note claims. Held as literals from
     its Table 7, never read from marketing/, which is gitignored.

Negative controls, all six run on every invocation.
"""

import ast
import io
import sys
from contextlib import redirect_stderr
from pathlib import Path

REPO = Path(__file__).resolve().parent
SRC = REPO / "app.py"

# Transcribed from Manning and Aguirre, NBER w34705, Table 7, "Complete list
# of high-vulnerability occupations (n = 10)", against the occupation titles
# this app uses. Literals on purpose: the expectation must not come from the
# thing under test, nor from marketing/adaptive_capacity_occupations.csv,
# which is generated by us and is not in every clone.
VULNERABLE = [
    ("Office Clerks, General", "High school diploma or equivalent"),
    ("Secretaries and Administrative Assistants, Except Legal, Medical, and Executive",
     "High school diploma or equivalent"),
    ("Medical Secretaries and Administrative Assistants", "High school diploma or equivalent"),
    ("Insurance Sales Agents", "High school diploma or equivalent"),
    ("Court, Municipal, and License Clerks", "High school diploma or equivalent"),
    ("Payroll and Timekeeping Clerks", "High school diploma or equivalent"),
    ("Eligibility Interviewers, Government Programs", "High school diploma or equivalent"),
    ("Property Appraisers and Assessors", "Bachelor's degree"),
    ("Tax Examiners and Collectors, and Revenue Agents", "Bachelor's degree"),
]
SUB_BACHELORS_EXPECTED = 7      # of the nine above that resolve; the tenth,
                                # door-to-door sales workers, needs no
                                # credential and is 5,000 workers.
NOTE_MUST_CARRY = [
    ("the correlation half", ["37.1 million", "26.5 million", "positively correlated"]),
    ("the baseline half", ["6.1 million", "high school diploma", "113,000"]),
]

# Functions allowed to read the exposure names. Everything here renders or
# resolves; none of them returns money.
EXPOSURE_READERS = {
    # Resolves a band for one occupation. Returns a dict of strings.
    "get_ai_exposure_for_major",
    # The module itself, on screen, and its per-scenario inner renderer.
    "render_ai_risk_section",
    "_render_one",
    # The module's only appearance in the report.
    "_pdf_module_sections",
    # These two read the LABEL and nothing else, for the "careers this major
    # leads to" section, which is a different feature that happens to want a
    # human name for a SOC group. They never touch risk_level or score.
    "render_major_careers",
    "_pdf_major_careers_section",
}
EXPOSURE_NAMES = {"AI_EXPOSURE_BY_SOC_GROUP", "get_ai_exposure_for_major",
                  "AI_EXPOSURE_CAPACITY_NOTE"}


def model():
    import analyze_model
    with redirect_stderr(io.StringIO()):
        return analyze_model.load_model_layer()


def function_source(src, tree, name):
    """The source text of one top-level function, for scoped string checks."""
    lines = src.splitlines()
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name == name:
            return "\n".join(lines[node.lineno - 1:node.end_lineno])
    return None


def readers(tree):
    """{function name: names it reads} for every function touching the module."""
    found = {}
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        used = {n.id for n in ast.walk(node) if isinstance(n, ast.Name)} & EXPOSURE_NAMES
        if used:
            found[node.name] = used
    return found


def enclosing(tree, name):
    """The top-level function containing a nested def, for readability."""
    for node in tree.body:
        if isinstance(node, ast.FunctionDef):
            for sub in ast.walk(node):
                if isinstance(sub, ast.FunctionDef) and sub.name == name and sub is not node:
                    return node.name
    return name


def check(ns, src, tree):
    problems = []
    groups = ns["AI_EXPOSURE_BY_SOC_GROUP"]

    # 1. well formed and monotone
    bands = {"Low": [], "Medium": [], "High": []}
    for key, entry in groups.items():
        for field in ("label", "risk_level", "score", "rationale"):
            if not entry.get(field):
                problems.append(f"  group {key} has no {field}")
        level = entry.get("risk_level")
        if level not in bands:
            problems.append(f"  group {key} has risk_level {level!r}, "
                            f"which is not Low, Medium or High")
        elif not isinstance(entry.get("score"), int):
            problems.append(f"  group {key} has a non-integer score {entry.get('score')!r}")
        else:
            bands[level].append(entry["score"])
    if all(bands.values()):
        if not max(bands["Low"]) < min(bands["Medium"]) < max(bands["Medium"]) < min(bands["High"]):
            problems.append(
                f"  the bands are not monotone in score: Low reaches {max(bands['Low'])}, "
                f"Medium runs {min(bands['Medium'])} to {max(bands['Medium'])}, High starts at "
                f"{min(bands['High'])}. A band that overlaps its neighbor makes the number and "
                f"the word disagree, and only the number is sortable.")

    # 2. every group in the data has a band
    unmapped = sorted({v.get("soc_major_group") for v in ns["MAJOR_DATA"].values()}
                      - set(groups) - {None, ""})
    if unmapped:
        problems.append(f"  SOC groups in MAJOR_DATA with no band: {unmapped}. Those "
                        f"occupations fall to the Unclassified placeholder, which is right "
                        f"for a genuinely unmapped major and wrong for a whole group.")

    # 3. the module moves no money
    for fn, names in sorted(readers(tree).items()):
        if fn in EXPOSURE_READERS:
            continue
        owner = enclosing(tree, fn)
        if owner in EXPOSURE_READERS:
            continue
        problems.append(f"  {fn}() reads {sorted(names)} and is not an allowed reader. "
                        f"This module is display-only: it moves no salary, no loan and no "
                        f"premium. If {fn} really should render it, add it to "
                        f"EXPOSURE_READERS with a reason.")

    # 4. the steering is gone
    if "def get_lower_risk_alternative_major" in src:
        problems.append("  get_lower_risk_alternative_major is back. It ranked occupations "
                        "by exposure and offered the nearest-paid Low-band one as an "
                        "alternative, which is advice resting on exposure as a proxy for "
                        "harm. The paper this module now cites measures that proxy and "
                        "finds it runs the wrong way at the top of the distribution.")
    # SCOPED TO THE RENDERER, not to the file. A whole-file search for the
    # phrase flags this module's own comment and the Methodology paragraph
    # explaining the removal, both of which are in the past tense and both of
    # which should stay. What must not come back is a RECOMMENDATION on
    # screen, so the test is what the renderer contains.
    body = function_source(src, tree, "render_ai_risk_section")
    if body is None:
        problems.append("  render_ai_risk_section is gone; the module no longer renders.")
    else:
        if "alternative" in body.lower():
            problems.append("  render_ai_risk_section mentions an 'alternative' again. The "
                            "module states a band and its rationale; suggesting a different "
                            "occupation on exposure grounds is advice, and it rests on the "
                            "proxy the cited paper measures and finds runs the wrong way.")
        if "st.info(" in body:
            problems.append("  render_ai_risk_section has an st.info back. Its only st.info "
                            "was the steering box.")
    # And the prose has to say the suggestion went, because prose describing a
    # deleted feature is what survives a deletion. CLAUDE.md records the same
    # failure against the discounting switch, which left the Methodology
    # describing a checkbox that was no longer there.
    if "That suggestion has been removed." not in src:
        problems.append("  the Methodology no longer records that the lower-exposure "
                        "suggestion was removed. A reader who used to see it gets no "
                        "explanation, and the next editor has nothing telling them why "
                        "it must not come back.")

    # 5. both halves of the note
    note = ns.get("AI_EXPOSURE_CAPACITY_NOTE", "")
    if not note:
        problems.append("  AI_EXPOSURE_CAPACITY_NOTE is missing entirely.")
    else:
        for half, needles in NOTE_MUST_CARRY:
            missing = [n for n in needles if n not in note]
            if missing:
                problems.append(
                    f"  the capacity note has lost {half}: {missing} absent. Both halves or "
                    f"neither. The correlation alone reads as a reason to stop worrying; the "
                    f"vulnerability alone reads as a reason to avoid a field.")

    # 6. both surfaces
    for surface, marker in (("the screen renderer", "st.markdown(AI_EXPOSURE_CAPACITY_NOTE)"),
                            ("the PDF", "AI_EXPOSURE_CAPACITY_NOTE.split")):
        if marker not in src:
            problems.append(f"  {surface} no longer renders the capacity note "
                            f"({marker!r} not found). The report used to print the band with "
                            f"no qualification at all, which is the half that reads as a "
                            f"warning.")

    # 7. the paper's own list, against our data
    md = ns["MAJOR_DATA"]
    sub_bachelors = 0
    for title, education in VULNERABLE:
        if title not in md:
            problems.append(f"  {title!r} is in the paper's high-vulnerability table and not "
                            f"in MAJOR_DATA. A missing title is inert rather than loud, so "
                            f"the note's claim about it would quietly stop being checkable.")
            continue
        got = md[title].get("typical_education")
        if got != education:
            problems.append(f"  {title!r}: BLS entry education is {got!r}, transcribed as "
                            f"{education!r}. The note counts on this split.")
        if got != "Bachelor's degree":
            sub_bachelors += 1
    if sub_bachelors != SUB_BACHELORS_EXPECTED:
        problems.append(f"  {sub_bachelors} of the paper's listed occupations are entered "
                        f"below a bachelor's, transcribed as {SUB_BACHELORS_EXPECTED}. The "
                        f"note's whole point is that this group sits on the counterfactual "
                        f"side of the comparison.")
    return problems


def controls(ns, src, tree):
    """Break it six ways; each must be caught, and each must actually apply."""
    fired = []

    def run(label, mutate_ns=None, mutate_src=None, expect=""):
        ns2 = dict(ns)
        src2 = src
        if mutate_ns:
            ns2 = mutate_ns(ns2)
        if mutate_src:
            src2 = mutate_src(src2)
            if src2 == src:
                return f"control {label!r} did not apply: the source is unchanged"
        got = check(ns2, src2, ast.parse(src2) if mutate_src else tree)
        if not any(expect in p for p in got):
            return (f"control {label!r} did not fire (expected {expect!r} in the report; "
                    f"got {got[:1] or 'nothing'})")
        fired.append(label)
        return None

    def bump_low(n):
        g = dict(n["AI_EXPOSURE_BY_SOC_GROUP"])
        g["35"] = {**g["35"], "score": 99}
        return {**n, "AI_EXPOSURE_BY_SOC_GROUP": g}

    def drop_rationale(n):
        g = dict(n["AI_EXPOSURE_BY_SOC_GROUP"])
        g["43"] = {**g["43"], "rationale": ""}
        return {**n, "AI_EXPOSURE_BY_SOC_GROUP": g}

    def trim_note(n):
        head = n["AI_EXPOSURE_CAPACITY_NOTE"].split("\n\n")[0]
        return {**n, "AI_EXPOSURE_CAPACITY_NOTE": head}

    def wrong_education(n):
        md = dict(n["MAJOR_DATA"])
        md["Office Clerks, General"] = {**md["Office Clerks, General"],
                                        "typical_education": "Bachelor's degree"}
        return {**n, "MAJOR_DATA": md}

    fails = [
        run("a Low score above the Medium band", mutate_ns=bump_low, expect="not monotone"),
        run("a band with no rationale", mutate_ns=drop_rationale, expect="has no rationale"),
        run("the note trimmed to its reassuring half", mutate_ns=trim_note,
            expect="lost the baseline half"),
        run("a vulnerable occupation reclassified as a degree job",
            mutate_ns=wrong_education, expect="entered below a bachelor's"),
        run("the steering box comes back in the renderer",
            mutate_src=lambda t: t.replace(
                '        st.caption(info["rationale"])\n        return info["risk_level"]',
                '        st.caption(info["rationale"])\n        st.info("alternative")\n'
                '        return info["risk_level"]', 1),
            expect="mentions an 'alternative' again"),
        run("the PDF stops printing the note",
            mutate_src=lambda t: t.replace("AI_EXPOSURE_CAPACITY_NOTE.split", "_none.split"),
            expect="the PDF no longer renders"),
        run("a money function reads the bands",
            mutate_src=lambda t: t.replace(
                "def calculate_roi(", "def _leak():\n    return AI_EXPOSURE_BY_SOC_GROUP\n\n\ndef calculate_roi(", 1),
            expect="_leak() reads"),
    ]
    return [f for f in fails if f], fired


def main():
    src = SRC.read_text()
    tree = ast.parse(src)
    ns = model()
    problems = check(ns, src, tree)
    control_failures, fired = controls(ns, src, tree)
    if problems or control_failures:
        print("check_ai_exposure FAILED\n")
        for line in problems + [f"  {c}" for c in control_failures]:
            print(line)
        return 1
    print(f"check_ai_exposure OK: {len(ns['AI_EXPOSURE_BY_SOC_GROUP'])} bands, monotone and "
          f"complete; the module reads into {len(EXPOSURE_READERS)} renderers and no money "
          f"function; the capacity note carries both halves and reaches both surfaces; "
          f"{len(VULNERABLE)} occupations from the paper's table check out. "
          f"{len(fired)} negative controls fired.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
