#!/usr/bin/env python3
"""Every model-dependent figure on the counselor decks still reproduces.

    python3 check_deck_figures.py
    python3 check_deck_figures.py --self-test    # the negative controls, no decks needed

WHY THIS EXISTS. `presentation/` is gitignored, so the two decks and the two
handouts had no guard at all while every other published surface here has one:
the book has check_book_figures, the infographics have check_chart_basis and
check_chart_prose, the app has eleven. An audit on 2026-09-23 found deck figures
from THREE different model eras sitting beside each other:

  $56,626   an LA high school baseline scaled by the ALL-OCCUPATIONS metro index,
            which the model stopped using on 2026-09-22
  $174k     a ten-year gain computed before the 2026-08-18 real-units baseline
            correction; the same scenario now reads about $406,000
  "13 of 48" the same era, now 3 of 48
  $1,390    California community-college tuition from the NCES dict, superseded
  $3,890    by the IPEDS CSV the app actually reads on 2026-08-20

A deck figure has no denominator, no reader who can check it and, until now,
nothing that recomputes it. The $3,890 case is the sharpest: it is STILL a live
constant in app.py (COMMUNITY_COLLEGE_COA_DEFAULT, the CSV-absent fallback), so
grepping the repo CONFIRMS the stale number. Only re-deriving finds it.

WHAT IT DOES. Two halves, and the second is the one that cannot quietly narrow:

  1. FIGURES. Each check derives a value from app.py's own model or from a
     committed dataset, renders it the ways a deck may legitimately write it,
     and asserts one of those renderings is on the named deck. The expectation
     is never read off the decks, which is the rule this repo states everywhere
     (`check_chart_axes`, the residency guard): a check that derives its
     expectation from the thing under test asserts only that it equals itself.
  2. COVERAGE. Every money figure, comma-grouped integer and percentage in the
     decks' visible text, plus every headline `stat-num`/`big-number` value,
     must be accounted for by a check or listed in EXEMPT with a reason. So a
     NEW figure added to a deck fails this guard until it is either reproduced
     or excused. Without that half the guard silently stops covering the deck
     as the deck grows, which this repo rates worse than no guard at all.

ITS LIMITS, NAMED RATHER THAN DISCOVERED LATER:

  - **A bare small integer in prose is checked but NOT coverage-required.**
    "162 colleges across 39 states" and "3 of the 48" have explicit checks, and
    a new one like them would be missed by the sweep, because requiring every
    loose integer would drag in every year, step number and list count on the
    page. Money, thousands-separated counts, percentages and headline figures
    are the classes where a stale number is both most damaging and least
    visible, and those are required.
  - **Rounding is tolerated, drift is not.** A check accepts the exact figure,
    the nearest hundred, the nearest thousand and the $Nk/$N.NM forms, all
    derived from the computed value. So it cannot catch a deck that rounds
    badly; it is aimed at a figure from a different model era, which is off by
    tens of percent rather than by a hundred dollars.
  - **It says nothing about prose.** "It cuts both ways" beside a corrected
    count is this guard's blind spot; a count that moved from 13 to 3 changes
    what the sentence should say and only a person can see that.

IT SKIPS LOUDLY WHEN `presentation/` IS ABSENT and exits 0, which is every
clone and every CI run, and is the documented contract the three chart guards
already follow. Reporting OK over zero files would be worse than no check.
guards.yml discovers `check_*.py` dynamically, so this joined CI the day it was
committed and will skip there forever; it is a LOCAL guard in practice, and the
decks are a local artifact.

THE CALL SHAPE MATTERS, and getting it wrong is how the audit first produced a
$749,600 premium for a radiologic technologist. `enrollment_years` is
`pre_earnings_years(title, program_years)`, NOT `program_years` -- they differ
for every occupation carrying a training overlay -- and `working_years` is 0
unless the path is the part-time community-college one.
"""
import argparse
import html as html_mod
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent
PRESENTATION = REPO / "presentation"
# The four surfaces that quote the model. The handouts are generated by
# presentation/build_handout.py, which carries its own copy of the result
# table, so they drift exactly as the decks do and are checked the same way.
DECKS = {"hs": "index.html", "cc": "community_college.html",
         "hs_handout": "handout-hs.html", "cc_handout": "handout-cc.html"}
DECK_ONLY = ("hs", "cc")
HANDOUTS = ("hs_handout", "cc_handout")
EVERYWHERE = DECK_ONLY + HANDOUTS

CITY_LA = "Los Angeles, CA"
# The table on both result slides holds these constant, so only the career
# changes. They are INPUTS, and the figures derived from them are the outputs
# this guard checks.
LOAN, RATE, STRATEGY = 30_000.0, 6.5, "Standard 10-Year"


# ---------------------------------------------------------------- renderings

def money_forms(v: float) -> list:
    """Every way a deck may legitimately write one derived money figure.

    All four are computed from `v`; none is typed. The k and M forms exist
    because the decks write "$42k behind" and "$2.0M ahead" where the full
    figure would not fit a stat band.
    """
    v = float(v)
    sign = "-" if v < 0 else ""
    a = abs(v)
    out = [f"{sign}${a:,.0f}",
           f"{sign}${round(a, -2):,.0f}",
           f"{sign}${round(a, -3):,.0f}"]
    if a >= 1_000:
        out.append(f"{sign}${round(a / 1_000):,.0f}k")
    if a >= 100_000:
        out.append(f"{sign}${a / 1_000_000:.1f}M")
    # A premium is written with its sign on the deck ("+$581,000"); a break-even
    # never is. Offer both so one check covers the column it appears in.
    if v > 0:
        out += ["+" + s for s in list(out)]
    if v < 0:
        # A deck may put the direction in words instead of in a sign:
        # "Podiatry: $42k behind a high school grad". Accepting the unsigned
        # magnitude is what lets one check cover both conventions, and it is
        # why this guard cannot catch a SIGN error. It is aimed at a figure
        # from a different model era, which is wrong by tens of percent.
        out += [s.lstrip("-") for s in list(out)]
    return sorted(set(out))


def count_forms(n: int) -> list:
    return sorted({f"{int(n):,}", str(int(n))})


def pct_forms(x: float) -> list:
    """A share written as the deck writes it: whole percent, or one decimal."""
    return sorted({f"{round(x * 100):.0f}%", f"{x * 100:.1f}%"})


# ------------------------------------------------------------------ the deck

TOKEN = re.compile(r"\$\s*-?[\d,]+(?:\.\d+)?\s*[kKmM]?\b"
                   r"|\b\d{1,3}(?:,\d{3})+\b"
                   r"|\b\d+(?:\.\d+)?%")
HEADLINE = re.compile(r'<div class="(?:stat-num|big-number)">(.*?)</div>', re.S)


def visible(raw: str) -> str:
    """The deck's reader-facing text, normalised so one spelling matches.

    Strips style, script and comments first: the stylesheet is full of numbers
    (`0.85em`, `#1a56db`) and none of them is a claim about anything.
    """
    t = re.sub(r"(?is)<(style|script)\b.*?</\1>", " ", raw)
    t = re.sub(r"(?s)<!--.*?-->", " ", t)
    t = re.sub(r"<[^>]+>", " ", t)
    t = html_mod.unescape(t)
    # &minus;, en dash and em dash all arrive as a sign in front of money.
    t = t.replace("−", "-").replace("–", "-").replace("—", "-")
    t = t.replace("\xa0", " ")
    # "- $35,400" and "-$35,400" are the same claim.
    t = re.sub(r"-\s+\$", "-$", t)
    return re.sub(r"\s+", " ", t)


def deck_tokens(raw: str) -> set:
    """Everything on this deck that must be accounted for."""
    toks = set(TOKEN.findall(visible(raw)))
    for m in HEADLINE.finditer(raw):
        cell = visible(m.group(1))
        toks |= set(TOKEN.findall(cell))
        # A headline that is a bare count ("836", "50") carries no separator and
        # would escape the sweep, and those are the figures a deck is read for.
        if re.fullmatch(r"\d+", cell.strip()):
            toks.add(cell.strip())
    return {t.replace(" ", "") for t in toks}


# ------------------------------------------------------------- the model layer

def load_model():
    """app.py's sections 1 and 2, the way analyze_model.py loads them."""
    src = (REPO / "app.py").read_text()
    m = re.search(r"^# =+\n# 3\. PAGE CONFIG & SESSION STATE", src, re.M)
    if not m:
        sys.exit("check_deck_figures: app.py's section 3 banner moved; this "
                 "script execs everything above it as the model layer.")
    ns = {"__name__": "deck_figure_guard", "__file__": str(REPO / "app.py")}
    exec(compile(src[:m.start()], str(REPO / "app.py"), "exec"), ns)
    return ns


def premium(ns, major_data, title, *, years=10, loan=0.0, idx=1.0, col=100.0,
            oop=0.0):
    """The earnings premium the app would show, for one occupation.

    `enrollment_years` is pre_earnings_years, not program_years: for an
    occupation with a training overlay the earnings curve starts at the
    bachelor's and the baseline must start there too (CLAUDE.md, "Both sides of
    the ROI comparison must agree what year 0 is"). Passing program_years here
    reported a podiatrist as $237,093 behind at ten years against a true
    $41,713, which is the shape of error this whole guard exists to catch.
    """
    saved = ns.get("MAJOR_DATA")
    ns["MAJOR_DATA"] = major_data
    try:
        pyrs = ns["program_years_for_major"](title)
        enr = ns["pre_earnings_years"](title, pyrs)
        r = ns["compute_scenario_results"](
            major_name=title, loan_amount=loan, interest_rate=RATE,
            repayment_strategy=STRATEGY, personal_contribution=oop,
            col_index=col, roi_window_years=years, hs_wage_index=idx,
            enrollment_years=enr, working_years=0,
            baseline_start_age=ns["baseline_start_age_for"](pyrs, enr, title),
            include_fees=True)
        return r
    finally:
        ns["MAJOR_DATA"] = saved


def breakeven(ns, major_data, title):
    saved = ns.get("MAJOR_DATA")
    ns["MAJOR_DATA"] = major_data
    try:
        pyrs = ns["program_years_for_major"](title)
        enr = ns["pre_earnings_years"](title, pyrs)
        out = ns["find_breakeven_loan"](
            title, RATE, STRATEGY, col_index=100.0, roi_window_years=10,
            hs_wage_index=1.0, enrollment_years=enr, working_years=0,
            baseline_start_age=ns["baseline_start_age_for"](pyrs, enr, title),
            include_fees=True)
        return out.get("breakeven_loan")
    finally:
        ns["MAJOR_DATA"] = saved


# ------------------------------------------------------------------ the checks

def build_checks(ns, verbose=False):
    """(label, forms, files) triples. `forms` is what the deck may say."""
    import pandas as pd

    checks = []

    def add(label, files, forms):
        checks.append((label, tuple(files), tuple(forms)))

    say = (lambda s: print(f"    {s}")) if verbose else (lambda s: None)

    # --- committed datasets, no model run -------------------------------
    coa = pd.read_csv(REPO / "data" / "college_coa_clean.csv")
    career = ns["build_major_data"](ns["CAREERS_CSV_PATH_NATIONAL"],
                                    mode=ns["DATASET_MODE_CAREER"])
    major = ns["build_major_data"](ns["CAREERS_CSV_PATH_NATIONAL"],
                                   mode=ns["DATASET_MODE_MAJOR"])
    cc = pd.read_csv(REPO / "data" / "cc_costs_clean.csv")
    gd = pd.read_csv(REPO / "data" / "graduate_debt_clean.csv")

    add("colleges in the cost file", EVERYWHERE, count_forms(len(coa)))
    add("careers in Career mode", EVERYWHERE, count_forms(len(career)))
    add("majors in Major mode", EVERYWHERE, count_forms(len(major)))
    add("career + major paths", DECK_ONLY, count_forms(len(career) + len(major)))
    add("cities", DECK_ONLY, count_forms(len(ns["CITY_DATA"])))
    # Graduate and professional schools publishing a debt median: everything in
    # the field-of-study file that is not a bachelor's row.
    add("graduate and professional schools", DECK_ONLY,
        count_forms(gd[gd["credential"] != "bachelor"]["UNITID"].nunique()))

    states = {s for s in cc["state"] if s in ns["US_STATES"]}
    add("states with a community-college price", DECK_ONLY, count_forms(len(states)))

    med = float(cc["in_district"].median())
    add("national median in-district tuition", ("cc", "cc_handout"), money_forms(med))
    add("two years of it", ("cc",), money_forms(med * 2))
    ca = float(cc.loc[cc["state"] == "CA", "in_district"].iloc[0])
    add("California in-district tuition", ("cc",), money_forms(ca))
    add("two years of California", ("cc",), money_forms(ca * 2))

    assoc_cols = (coa["programs_assoc"].fillna("").astype(str).str.strip() != "").sum()
    add("colleges awarding an associate's", ("cc",), count_forms(assoc_cols))

    # The residency gap, the three figures the school-search caption quotes.
    gap = coa[coa["in_state_coa"].notna() & coa["out_of_state_coa"].notna()
              & (coa["out_of_state_coa"] > coa["in_state_coa"])]
    add("share of colleges charging more out of state", ("hs",),
        pct_forms(len(gap) / len(coa)))
    per_year = float((gap["out_of_state_coa"] - gap["in_state_coa"]).median())
    add("median out-of-state gap a year", ("hs",), money_forms(per_year))
    add("that gap over four years", ("hs",), money_forms(per_year * 4))

    # --- federal borrowing constants ------------------------------------
    add("Parent PLUS aggregate limit", EVERYWHERE,
        money_forms(ns["PARENT_PLUS_AGGREGATE_LIMIT"]))
    add("Parent PLUS annual limit", EVERYWHERE,
        money_forms(ns["PARENT_PLUS_ANNUAL_LIMIT"]))
    add("dependent first-year Direct limit", EVERYWHERE,
        money_forms(ns["FEDERAL_DIRECT_ANNUAL_LIMITS"]["dependent"][1]))

    # --- Los Angeles, the slide the audit found three eras on ------------
    la = ns["build_major_data"](ns["CAREERS_CSV_PATH_NATIONAL"],
                                mode=ns["DATASET_MODE_CAREER"], city=CITY_LA)
    idx = ns["get_baseline_wage_index"](CITY_LA)
    col = ns["CITY_DATA"][CITY_LA]["col_index"]
    add("LA high school baseline", ("cc",),
        money_forms(ns["HS_GRAD_SALARY"] * idx))

    rad = "Radiologic Technologists and Technicians"
    add("LA radiologic technologist entry pay", ("cc",),
        money_forms(la[rad]["starting_salary"]))
    say("running the LA radiologic scenario")
    r = premium(ns, la, rad, idx=idx, col=col, oop=ca * 2)
    add("LA radiologic ten-year gain", ("cc",),
        money_forms(r["roi_result"]["earnings_premium"]))

    assoc = [t for t, e in la.items()
             if e.get("typical_education") == "Associate's degree"]
    add("associate's careers", ("cc",), count_forms(len(assoc)))
    say(f"sweeping {len(assoc)} LA associate's careers")
    below = sum(1 for t in assoc
                if premium(ns, la, t, idx=idx, col=col)["roi_result"]
                ["earnings_premium"] < 0)
    add("LA associate's careers below the baseline", ("cc",),
        count_forms(below))

    no_degree = [t for t, e in career.items()
                 if e.get("typical_education") in
                 ("High school diploma or equivalent",
                  "No formal educational credential")]
    add("careers needing no degree", ("cc",), count_forms(len(no_degree)))

    # --- the two result slides ------------------------------------------
    # WHICH SURFACE CARRIES WHICH FIGURE IS NOT UNIFORM, and assuming it was
    # produced four false failures on this guard's first run. The community
    # college DECK has no break-even column (its last column is the crossover
    # age) while both handouts do, and the same deck never states the monthly
    # payment. A row is therefore scoped per figure, not per row.
    HS_SIDE = ("hs", "hs_handout")
    CC_SIDE = ("cc", "cc_handout")
    ROWS = {
        # title: (files carrying pay and premium, files carrying the break-even)
        "Software Developers": (HS_SIDE, HS_SIDE),
        "Registered Nurses": (HS_SIDE, HS_SIDE),
        "Kindergarten Teachers, Except Special Education":
            (HS_SIDE + CC_SIDE, ("hs", "hs_handout", "cc_handout")),
        "Dental Hygienists": (CC_SIDE, ("cc_handout",)),
        "Respiratory Therapists": (CC_SIDE, ("cc_handout",)),
    }
    for title, (shown, be_files) in ROWS.items():
        say(f"running {title}")
        r = premium(ns, career, title, loan=LOAN)
        add(f"{title}: starting pay", shown,
            money_forms(career[title]["starting_salary"]))
        add(f"{title}: ten-year premium", shown,
            money_forms(r["roi_result"]["earnings_premium"]))
        add(f"{title}: debt it can carry", be_files,
            money_forms(breakeven(ns, career, title)))
        if title == "Software Developers":
            add("the monthly payment every row shares",
                ("hs",) + HANDOUTS,
                money_forms(r["repayment_result"]["monthly_payment"]))

    # --- the findings slide ---------------------------------------------
    say("running Podiatrists at 10 and 30 years")
    add("podiatry, behind at ten years", ("hs",),
        money_forms(premium(ns, career, "Podiatrists", years=10)
                    ["roi_result"]["earnings_premium"]))
    add("podiatry, ahead at thirty", ("hs",),
        money_forms(premium(ns, career, "Podiatrists", years=30)
                    ["roi_result"]["earnings_premium"]))

    bach = [t for t, e in career.items()
            if e.get("typical_education") == "Bachelor's degree"]
    say(f"sweeping {len(bach)} bachelor's careers at zero debt")
    fail = sum(1 for t in bach
               if premium(ns, career, t)["roi_result"]["earnings_premium"] < 0)
    add("bachelor's careers behind at ten years, no debt", ("hs",),
        pct_forms(fail / len(bach)))

    # --- the school searches --------------------------------------------
    say("running the two school searches")
    ns["MAJOR_DATA"] = career
    fam = next(k for k, v in ns["CIP_FAMILY_TITLES"].items()
               if v == "Computer & Information Sciences")
    hs_hits = ns["search_schools_by_budget"](fam, "Bachelor's degree", 25_000,
                                             home_state=None, limit=100_000)
    add("colleges teaching CS under the budget", ("hs",),
        count_forms(len(hs_hits)))
    add("states they sit in", ("hs",), count_forms(hs_hits["STABBR"].nunique()))
    cc_hits = ns["search_schools_by_budget"](fam, "Associate's degree", 15_000,
                                             home_state="CA", limit=100_000)
    add("colleges teaching the associate's under the budget", ("cc",),
        count_forms(len(cc_hits)))
    add("states they sit in (associate's)", ("cc",),
        count_forms(cc_hits["STABBR"].nunique()))
    add("of them in California", ("cc",),
        count_forms((cc_hits["STABBR"] == "CA").sum()))

    return checks


# ------------------------------------------------------- tokens with no model

EXEMPT = {
    # The NY Fed's Household Debt and Credit report, 2026Q2, read from the PDF
    # at newyorkfed.org on 2026-09-23. No repo source; re-read at the source
    # when the deck is next sent, and expect a newer quarter.
    "10.6%": "NY Fed Household Debt and Credit, 2026Q2, verified at source",
    "10.3%": "the same report's prior quarter, quoted as the comparison",
    "$1.65": "outstanding student debt, $1.65 trillion, same report",
    # Inputs the decks hold constant so that only the career varies. Checking
    # them would assert that a slide says what it says.
    "$30,000": "the loan every result row borrows, an input",
    "6.5%": "the rate every result row pays, an input",
    "$25,000": "the budget the bachelor's search is run at, an input",
    "$15,000": "the budget the associate's search is run at, an input",
    "$40,000": "a threshold in prose about how thin the weakest rows are",
    # Illustration, not a figure from any dataset.
    "$45,000": "an illustrative sticker price in the 2026-rules paragraph",
    "$50,000": "an illustrative loan in the kindergarten-teacher sentence",
    # RAP's published payment band. studentaid.gov's own chart, and
    # check_rap_payment_table.py already asserts the app reproduces it row by
    # row; repeating that here would be a second, weaker copy of that check.
    "1%": "the floor of RAP's published band, guarded by check_rap_payment_table",
    "10%": "the ceiling of RAP's published band, same guard",
    # Set on KDP, not computed here.
    "$19.95": "the paperback price, set on KDP",
    "$9.99": "the Kindle price, set on KDP",
}


# ------------------------------------------------------------------- checking

def appears(form: str, text: str) -> bool:
    """Is this rendering really on the page, as a figure rather than as a run
    of digits inside a larger one?

    A PLAIN SUBSTRING TEST MAKES EVERY SHORT CHECK VACUOUS, which this guard
    shipped with for one draft: `"3" in text` is true of any page containing a
    three, so the check that 3 of the 48 LA associate's careers fall below the
    baseline passed on every possible deck, including one that said 13. That is
    the assertion-that-cannot-fail this repo rates worse than no assertion, and
    it is the exact figure the 2026-09-23 audit found wrong. Digits, a comma, a
    period, a dollar sign or a percent on either side means this is part of some
    other number.
    """
    return re.search(r"(?<![\d,.$])" + re.escape(form) + r"(?![\d,.%])",
                     text) is not None


def run(texts: dict, checks: list) -> list:
    """Every failure, as a list of sentences. Empty means the decks are clean."""
    problems = []
    claimed = set()

    for label, files, forms in checks:
        claimed |= {f.replace(" ", "") for form in forms
                    for f in TOKEN.findall(form)}
        claimed |= {f.replace(" ", "") for f in forms if re.fullmatch(r"\d+", f)}
        for key in files:
            if key not in texts:
                continue
            seen = visible(texts[key])
            if not any(appears(form, seen) for form in forms):
                problems.append(
                    f"{DECKS[key]}: {label} does not appear. The model says "
                    f"{forms[0]} (also accepted: {', '.join(forms[1:]) or 'nothing else'}).")

    for key, raw in texts.items():
        for tok in sorted(deck_tokens(raw)):
            if tok in claimed or tok in EXEMPT:
                continue
            problems.append(
                f"{DECKS[key]}: {tok} is not reproduced by any check and is not "
                f"in EXEMPT. Add a check that derives it, or exempt it with a "
                f"reason.")
    return problems


def read_decks() -> dict:
    return {k: (PRESENTATION / name).read_text() for k, name in DECKS.items()}


# --------------------------------------------------------------- self-test

def self_test() -> int:
    """Negative controls. Each asserts its own anchor actually applied, because
    a control that silently did not edit anything reads as a pass."""
    ok = True

    def control(name, mutate, expect):
        nonlocal ok
        texts = {"hs": FIXTURE_HS, "cc": FIXTURE_CC}
        before = texts["hs"]
        texts["hs"] = mutate(texts["hs"])
        if texts["hs"] == before:
            print(f"  INCONCLUSIVE  {name}: the edit did not apply")
            ok = False
            return
        hits = run(texts, FIXTURE_CHECKS)
        if any(expect in h for h in hits):
            print(f"  caught        {name}")
        else:
            print(f"  MISSED        {name}: expected a failure naming {expect!r}")
            ok = False

    # A deck that reproduces every check and carries no loose figure.
    if run({"hs": FIXTURE_HS, "cc": FIXTURE_CC}, FIXTURE_CHECKS):
        print("  FAILED        the positive control: a correct deck must pass")
        for h in run({"hs": FIXTURE_HS, "cc": FIXTURE_CC}, FIXTURE_CHECKS):
            print(f"                {h}")
        ok = False
    else:
        print("  passes        a correct deck")

    control("a figure from an older model era",
            lambda t: t.replace("$105,210", "$98,400"), "starting pay")
    control("a figure deleted outright",
            lambda t: t.replace("<div>$105,210</div>", "<div>see the tool</div>"),
            "starting pay")
    control("a new money figure nobody checks",
            lambda t: t.replace("</body>", "<p>Median debt is $31,175.</p></body>"),
            "$31,175")
    control("a new headline count nobody checks",
            lambda t: t.replace("</body>",
                                '<div class="stat-num">7412</div></body>'),
            "7412")
    # The control for this guard's OWN first bug: a short count matched as a
    # substring passes on any page containing that run of digits, so "3" was
    # satisfied by the 3 inside "$105,210" and the check could never fail.
    control("a short count changed, which a substring test would miss",
            lambda t: t.replace("<p>3 careers</p>", "<p>13 careers</p>"),
            "careers below")

    print("\nself-test", "OK" if ok else "FAILED")
    return 0 if ok else 1


FIXTURE_CHECKS = [
    ("starting pay", ("hs",), tuple(money_forms(105_210))),
    ("colleges", ("hs", "cc"), tuple(count_forms(5035))),
    # A short count, deliberately a digit that also occurs inside $105,210.
    ("careers below the baseline", ("hs",), tuple(count_forms(3))),
]
FIXTURE_HS = ("<html><style>.x{font-size:0.85em}</style><body>"
              "<div>$105,210</div><div class='stat-num'>5,035</div>"
              "<p>3 careers</p></body></html>")
FIXTURE_CC = "<html><body><div class='stat-num'>5,035</div></body></html>"


# -------------------------------------------------------------------- main

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--self-test", action="store_true",
                    help="run the negative controls; needs no decks")
    ap.add_argument("-v", "--verbose", action="store_true",
                    help="say which scenario is running")
    a = ap.parse_args()

    if a.self_test:
        return self_test()

    missing = [n for n in DECKS.values() if not (PRESENTATION / n).exists()]
    if missing:
        print("check_deck_figures: SKIPPED. presentation/ is gitignored, so "
              "the decks are not in this tree.")
        print(f"  not found: {', '.join(missing)}")
        return 0

    print("check_deck_figures: loading app.py's model layer")
    ns = load_model()
    checks = build_checks(ns, verbose=a.verbose)
    problems = run(read_decks(), checks)

    if problems:
        print(f"\nFAILED: {len(problems)} problem(s)\n")
        for p in problems:
            print(f"  {p}")
        return 1
    print(f"OK: {len(checks)} figures reproduce across {len(DECKS)} surfaces, "
          f"and every money figure, count and percentage on them is accounted "
          f"for.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
