#!/usr/bin/env python3
"""The landing page's link-preview card, built from a screenshot of the tool.

    python3 brand/build_calculator_og.py

WHY A SCREENSHOT AND NOT A COMPOSED CARD. The other og cards in this repo are
typeset from constants (build_guide_graphics.py) or cropped from a generated
hero (compose_og_card). Both describe the site in words. This one exists
because a person deciding whether to click a link about student loans is asking
"is this a real tool or another blog", and the only honest answer is the tool
itself with real numbers in it. Every figure in the shot is the live model
running the committed datasets, so it cannot promise a screen the visitor will
not get.

THE SUBJECT IS ONE STACKED BAR, AND THAT WAS MEASURED. Three candidates were
rendered and compared at 280px, which is roughly what Reddit shows in-feed: the
take-home metric columns became a grey wall of unreadable text, the compare-mode
pair of bars shrank into mush, and a SINGLE bar stayed legible -- the orange
loan block against the blue remainder still reads as a quantity at that size,
where digits do not. Bigger is not the choice here; fewer things is.

THE LEGEND STAYS even though every visible segment is already labelled inside
the bar. State tax is too thin to carry its own label, and per the chart's own
design note the legend is the only identity such a segment has. Cropping the
legend for tidiness would silently delete a tax from the picture.

THE SOURCE IS COMMITTED, because it cannot be regenerated by a script: it comes
from a browser against a running app. brand/sources/calculator-salaryflow-shot.png
was captured on 2026-08-15 from `streamlit run app.py --theme.base light`, at
`?test=1`, on the default single scenario -- UC Berkeley, in-state, Computer
Science, San Francisco, Annual -- cropped to the salary-flow bars at viewport
region (320, 505)-(1400, 710). Re-shoot it the same way if the layout moves,
and keep ?test=1 on: a bare local run writes to the production research tables.

NO HEADLINE IS DRAWN, for the reason compose_og_card gives: every platform
renders og:title beside the image, so baking words in prints them twice, and
text near an edge is the first thing a platform's own crop removes. The
wordmark on its bar is the exception, because a preview with no mark on it is
not attributable once it has been reposted.

FIT, NOT FILL. compose_og_card centre-crops a photograph to the card's aspect,
which is right for a photograph and wrong here: cropping a screenshot cuts
digits off a dollar amount. This scales to fit and pads with the page's own
background, so the numbers are always whole.
"""
import sys
from pathlib import Path

import numpy as np
from PIL import Image

sys.path.insert(0, str(Path(__file__).parent))
from build_guide_graphics import (                                # noqa: E402
    DEEP, DPI, OG_BAR, OG_H, OG_W, OUT, STATIC, SURFACE, canvas, wordmark)
import matplotlib.pyplot as plt                                   # noqa: E402

SOURCE = Path(__file__).parent / "sources" / "calculator-salaryflow-shot.png"
NAME = "feature-og-calculator-1200x630.png"
PAD = 28          # breathing room so the shot does not touch the card edge
# The Starting (Year 1) bar only. The shot holds both career stages side by
# side and the blank gutter between them was located rather than guessed: the
# columns from x=721 to x=786 carry no ink at all. Cropping at the gutter takes
# the left stage whole and cannot clip a segment. Trimmed here rather than in
# the committed source, so the original capture stays intact and the choice
# stays something this file records.
CROP = (0, 0, 721, 298)


def build() -> Path:
    if not SOURCE.exists():
        sys.exit(f"missing {SOURCE.relative_to(Path(__file__).parent.parent)} -- "
                 "see this file's docstring for how it was captured")
    shot = Image.open(SOURCE).convert("RGB").crop(CROP)

    panel_w, panel_h = OG_W - 2 * PAD, OG_H - OG_BAR - 2 * PAD
    scale = min(panel_w / shot.width, panel_h / shot.height)
    shot = shot.resize((max(1, int(shot.width * scale)),
                        max(1, int(shot.height * scale))), Image.LANCZOS)

    fig, ax = canvas(OG_W, OG_H)
    # The card's ground is the app's own surface, so the padding reads as the
    # page continuing rather than as a border someone drew.
    ax.add_patch(plt.Rectangle((0, OG_BAR), OG_W, OG_H - OG_BAR,
                               color=SURFACE, zorder=1, linewidth=0))
    left = (OG_W - shot.width) / 2
    bottom = OG_BAR + PAD + (panel_h - shot.height) / 2
    ax.imshow(np.asarray(shot), zorder=2, aspect="auto",
              extent=(left, left + shot.width, bottom, bottom + shot.height))
    ax.add_patch(plt.Rectangle((0, 0), OG_W, OG_BAR, color=DEEP, zorder=3,
                               linewidth=0))
    wordmark(fig, ax, 46, OG_BAR * 0.30, size=34, ink="#ffffff", muted="#b9c6d8")

    path = OUT / NAME
    fig.savefig(path, dpi=DPI, facecolor=SURFACE)
    plt.close(fig)

    STATIC.mkdir(exist_ok=True)
    dst = STATIC / NAME
    dst.write_bytes(path.read_bytes())
    print(f"  wrote {path.name} ({path.stat().st_size:,} bytes) -> {dst}")
    return dst


if __name__ == "__main__":
    build()
